name: Build Vite App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      npm_config_build_from_source: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Enable Corepack
        run: corepack enable

      - name: Clean install
        run: npm ci

      - name: Clean old build folder
        run: rm -rf abradabra

      - name: Build project
        run: npm run build

      - name: Move build output
        run: |
          mkdir -p abradabra
          cp -r dist/* abradabra/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: abradabra-build
          path: abradabra
