name: Build Abradabra Folder

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Delete old abradabra build
        run: rm -rf abradabra

      - name: Build project
        run: npm run build

      - name: Commit updated abradabra folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add abradabra

          git diff --staged --quiet || git commit -m "Update abradabra build [skip ci]"

          git push
